# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: Apache-2.0


name: Clang-Format Check

on: [pull_request, push]

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1) Add the official LLVM repository for clang-format-21
      - name: Add LLVM apt repo
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-21 main"
          sudo apt-get update

      # 2) Install clang-format-21 from that repo
      - name: Install clang-format-21
        run: |
          sudo apt-get install -y clang-format-21
          clang-format-21 --version

      # 3) Check formatting
      - name: Check formatting
        run: |
          # Specify file extensions to be checked
          FILES=$(git ls-files '*.cpp' '*.h' '*.cu' '*.cuh' '*.hh' '*.cc' '*.icc')
          
          # '-n' checks if files need reformatting
          # '--Werror' throws an error if formatting is incorrect
          clang-format-21 -style=file -n --Werror $FILES